#!/usr/bin/env python3
"""Generate a draw.io diagram from the per-layer map graphs.

This script consumes the JSON files produced under ``docs/map_layers/`` and
renders a draw.io-compatible XML with one page per layer. Nodes are positioned
according to the coordinates stored in the plan (when available) and annotated
with their location identifier. Travel edges using the same layer are rendered
as orthogonal connectors labelled with the verb list.
"""

from __future__ import annotations

import json
import math
import uuid
from pathlib import Path
from typing import Dict, Iterable, List, Tuple
from xml.etree.ElementTree import Element, SubElement, ElementTree

ROOT = Path(__file__).resolve().parents[1]
MAP_LAYERS_DIR = ROOT / "docs" / "map_layers"
OUTPUT_PATH = ROOT / "diagram" / "map_layers.drawio.xml"

# Default node size in draw.io units.
NODE_WIDTH = 160
NODE_HEIGHT = 60

# Auto-placement grid for nodes without coordinates.
GRID_X_STEP = 200
GRID_Y_STEP = 140


def load_layer_graphs() -> List[Tuple[str, Dict[str, any]]]:
    graphs: List[Tuple[str, Dict[str, any]]] = []
    if not MAP_LAYERS_DIR.exists():
        raise FileNotFoundError(f"Directory not found: {MAP_LAYERS_DIR}")
    for path in sorted(MAP_LAYERS_DIR.glob("*.json")):
        with path.open("r", encoding="utf-8") as handle:
            graphs.append((path.stem, json.load(handle)))
    if not graphs:
        raise RuntimeError("No layer graph JSON files found in docs/map_layers/")
    return graphs


def format_label(location_id: str) -> str:
    return location_id


def sanitize_coordinate(value: float, default: float) -> float:
    if value is None or math.isnan(value) or math.isinf(value):
        return default
    return value


def create_mxfile(pages: List[Tuple[str, Dict[str, any]]]) -> Element:
    mxfile = Element(
        "mxfile",
        {
            "host": "draw.io",
            "pages": str(len(pages)),
            "agent": "Generated by export_drawio_map.py",
            "version": "28.1.2",
        },
    )

    for index, (layer_name, graph) in enumerate(pages):
        page_id = f"page-{index+1}"
        diagram = SubElement(
            mxfile,
            "diagram",
            {
                "name": layer_name,
                "id": str(uuid.uuid4()),
            },
        )
        model = SubElement(
            diagram,
            "mxGraphModel",
            {
                "dx": "1024",
                "dy": "768",
                "grid": "1",
                "gridSize": "10",
                "guides": "1",
                "tooltips": "1",
                "connect": "1",
                "arrows": "1",
                "fold": "1",
                "page": "1",
                "pageScale": "1",
                "pageWidth": "1600",
                "pageHeight": "1200",
                "math": "0",
                "shadow": "0",
            },
        )
        root = SubElement(model, "root")
        SubElement(root, "mxCell", {"id": "0"})
        SubElement(root, "mxCell", {"id": "1", "parent": "0"})

        nodes = graph.get("nodes", [])
        node_ids: Dict[str, str] = {}
        auto_positions: Dict[str, Tuple[float, float]] = {}
        auto_index = 0

        for node in nodes:
            location_id = node.get("id")
            if not isinstance(location_id, str):
                continue
            position = node.get("position") or {}
            x = position.get("x")
            y = position.get("y")

            if x is None or y is None or (abs(float(x or 0.0)) < 1e-6 and abs(float(y or 0.0)) < 1e-6):
                grid_col = auto_index % 6
                grid_row = auto_index // 6
                x = 100 + grid_col * GRID_X_STEP
                y = 100 + grid_row * GRID_Y_STEP
                auto_positions[location_id] = (x, y)
                auto_index += 1

            x = sanitize_coordinate(float(x), 100.0)
            y = sanitize_coordinate(float(y), 100.0)

            cell_id = f"{page_id}-v-{len(node_ids)+1}"
            node_ids[location_id] = cell_id

            cell = SubElement(
                root,
                "mxCell",
                {
                    "id": cell_id,
                    "value": format_label(location_id),
                    "style": "rounded=1;whiteSpace=wrap;html=1;",
                    "vertex": "1",
                    "parent": "1",
                },
            )
            geometry = SubElement(
                cell,
                "mxGeometry",
                {
                    "x": f"{x:.2f}",
                    "y": f"{y:.2f}",
                    "width": str(NODE_WIDTH),
                    "height": str(NODE_HEIGHT),
                    "as": "geometry",
                },
            )
            geometry.attrib["as"] = "geometry"

        edge_index = 0
        for node in nodes:
            location_id = node.get("id")
            source_id = node_ids.get(location_id)
            if source_id is None:
                continue
            travels = node.get("travel") or []
            if not isinstance(travels, list):
                continue
            for travel in travels:
                action = travel.get("action")
                if (
                    not isinstance(action, list)
                    or not action
                    or action[0] != "goto"
                    or len(action) < 2
                ):
                    continue
                destination = action[1]
                target_id = node_ids.get(destination)
                if target_id is None:
                    # Skip inter-layer edges to avoid dangling references.
                    continue

                verbs = travel.get("verbs") or []
                if isinstance(verbs, Iterable):
                    label = ", ".join(str(v) for v in verbs if v)
                else:
                    label = ""

                edge_id = f"{page_id}-e-{edge_index+1}"
                edge_index += 1
                edge_cell = SubElement(
                    root,
                    "mxCell",
                    {
                        "id": edge_id,
                        "value": label,
                        "style": "edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;",
                        "edge": "1",
                        "source": source_id,
                        "target": target_id,
                        "parent": "1",
                    },
                )
                edge_geometry = SubElement(
                    edge_cell,
                    "mxGeometry",
                    {
                        "relative": "1",
                        "as": "geometry",
                    },
                )
                edge_geometry.attrib["as"] = "geometry"

    return mxfile


def main() -> int:
    pages = load_layer_graphs()
    mxfile = create_mxfile(pages)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    ElementTree(mxfile).write(OUTPUT_PATH, encoding="utf-8", xml_declaration=True)
    print(f"Draw.io map exported to {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
